server:
  port: 10000
spring:
  datasource:
    url: jdbc:mysql://192.168.1.233:3306/security?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: pw123456

mybatis:
  configuration:
    cache-enabled: false
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    auto-mapping-behavior: full
    default-executor-type: reuse
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  mapper-locations: classpath:mapper/*/*.xml